pipeline {
    agent any
    environment {
        DOCKERHUB_CREDENTIALS=credentials('DOCKERHUB')
    }
    stages {
        stage('Trigged') {
            steps {
                echo "Hello $DOCKERHUB_CREDENTIALS_USR from Slave"
            }
        }
        stage('Login Stage') {
          steps {
            echo "Login : Logging in . . ."
            sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
          }
        }
 
}